### ISSUE TITLE
File system race condition when reloading assets

### ISSUE THREAD

**Issue by sornas** [sornas/lingon#41]
I got this just now while re-loading a file. The asset loaded fine when I restarted.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }', src/asset/audio.rs:55:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We can either check if the file is done being written to in some way, or mark the file as "actually, try to load it again next frame" if the data parsing fails.

**Comment by sornas** [comment]
The line in question was
```
        let (header, data) = wav::read(&mut std::io::Cursor::new(bytes)).unwrap();
```

**Comment by FredTheDino** [comment]
I suspect the problem is the OS writing to the file continousely, and updating the timestamp. So we could solve it for that special case - but all new assets we add will have the same problem.

A more general solution would be to only load assets if they are older than 1s, or wait 20 frames to reload the data once. Adding a delay before we delegate to the actual loading.
